//@version=6
strategy('Q-Trend Strategy FTMO (No Repaint)', overlay = true, initial_capital = 1000000, pyramiding = 1, commission_value = 0.0, process_orders_on_close = true)

src = input(hlc3, 'Source', group = 'Main settings')
p = input.int(200, 'Trend period', group = 'Main settings', minval = 1)
atr_p = input.int(14, 'ATR Period', group = 'Main settings', minval = 1)

var float prev_m = na
var float prev_atr = na

h = ta.highest(src[1], p)
l = ta.lowest(src[1], p)
m = (h + l) / 2
atr_val = ta.atr(atr_p)

prev_m := m
prev_atr := atr_val

epsilon = prev_atr
longSignal = src[1] > prev_m + epsilon
shortSignal = src[1] < prev_m - epsilon

// Exit thresholds


// Entry logic
if longSignal and not (strategy.position_size > 0)
    trailStopLong = prev_atr
    trailOffsetLong = trailStopLong * 0.5
    strategy.entry('buy', strategy.long)
    size = 1
    entryMsg = "entry ETH/USDT buy " + str.tostring(close, "#.##") + " " + str.tostring(size, "#.#######") + " " + str.tostring(trailOffsetLong, "#.##") + " " + str.tostring(trailStopLong, "#.##")
    alert(entryMsg, alert.freq_once_per_bar)
    strategy.exit('Exit buy', 'buy', trail_points = trailStopLong, trail_offset = trailOffsetLong)
    
    


if shortSignal and not (strategy.position_size < 0)
    trailStopShort = prev_atr
    trailOffsetShort = trailStopShort * 0.5
    strategy.entry('sell', strategy.short)
    size = 1
    entryMsg = "entry ETH/USDT sell " + str.tostring(close, "#.##") + " " + str.tostring(size, "#.######") + " " + str.tostring(trailOffsetShort, "#.##") + " " + str.tostring(trailStopShort, "#.##")
    alert(entryMsg, alert.freq_once_per_bar)
    strategy.exit('Exit sell', 'sell', trail_points = trailStopShort, trail_offset = trailOffsetShort)
    